/*
 * Indexer
 *
 * Algorand ledger analytics API.
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use serde::{Deserialize, Serialize};

use crate::models::EvalDeltaKeyValue;

/// Application state delta.
pub type StateDelta = Vec<EvalDeltaKeyValue>;
