/*
 * Indexer
 *
 * Algorand ledger analytics API.
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use serde::{Deserialize, Serialize};

use crate::models::TealKeyValue;

/// Represents a key-value store for use in an application.
pub type TealKeyValueStore = Vec<TealKeyValue>;
