name: 'Setup API Tools'
description: 'Setup Rust, Bun, and Python dependencies for API tools'

runs:
  using: 'composite'
  steps:
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: 1.85.0
        components: rustfmt
    
    - uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest
    
    - name: Install uv
      uses: astral-sh/setup-uv@v5
    
    - name: Install bun dependencies
      working-directory: api
      shell: bash
      run: bun install
    
    - name: Install uv dependencies
      working-directory: api/oas_generator
      shell: bash
      run: uv sync --extra dev