/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

// Consolidated client
pub mod client;

// Parameter enums for type-safe API parameters
pub mod parameter_enums;

// Individual endpoint modules
pub mod abort_catchup;
pub mod account_application_information;
pub mod account_asset_information;
pub mod account_assets_information;
pub mod account_information;
pub mod add_participation_key;
pub mod append_keys;
pub mod delete_participation_key_by_id;
pub mod experimental_check;
pub mod generate_participation_keys;
pub mod get_application_box_by_name;
pub mod get_application_boxes;
pub mod get_application_by_id;
pub mod get_asset_by_id;
pub mod get_block;
pub mod get_block_hash;
pub mod get_block_logs;
pub mod get_block_time_stamp_offset;
pub mod get_block_txids;
pub mod get_config;
pub mod get_debug_settings_prof;
pub mod get_genesis;
pub mod get_ledger_state_delta;
pub mod get_ledger_state_delta_for_transaction_group;
pub mod get_light_block_header_proof;
pub mod get_participation_key_by_id;
pub mod get_participation_keys;
pub mod get_pending_transactions;
pub mod get_pending_transactions_by_address;
pub mod get_ready;
pub mod get_state_proof;
pub mod get_status;
pub mod get_supply;
pub mod get_sync_round;
pub mod get_transaction_group_ledger_state_deltas_for_round;
pub mod get_transaction_proof;
pub mod get_version;
pub mod health_check;
pub mod metrics;
pub mod pending_transaction_information;
pub mod put_debug_settings_prof;
pub mod raw_transaction;
pub mod raw_transaction_async;
pub mod set_block_time_stamp_offset;
pub mod set_sync_round;
pub mod shutdown_node;
pub mod simulate_transaction;
pub mod start_catchup;
pub mod swagger_json;
pub mod teal_compile;
pub mod teal_disassemble;
pub mod teal_dryrun;
pub mod transaction_params;
pub mod unset_sync_round;
pub mod wait_for_block;

/// Unified error type that can represent any API error from any endpoint
#[derive(Debug, thiserror::Error)]
pub enum AlgodApiError {
    #[error("Health_check error: {0:?}")]
    HealthCheck(health_check::HealthCheckError),
    #[error("Get_ready error: {0:?}")]
    GetReady(get_ready::GetReadyError),
    #[error("Metrics error: {0:?}")]
    Metrics(metrics::MetricsError),
    #[error("Get_genesis error: {0:?}")]
    GetGenesis(get_genesis::GetGenesisError),
    #[error("Swagger_json error: {0:?}")]
    SwaggerJson(swagger_json::SwaggerJsonError),
    #[error("Get_version error: {0:?}")]
    GetVersion(get_version::GetVersionError),
    #[error("Get_debug_settings_prof error: {0:?}")]
    GetDebugSettingsProf(get_debug_settings_prof::GetDebugSettingsProfError),
    #[error("Put_debug_settings_prof error: {0:?}")]
    PutDebugSettingsProf(put_debug_settings_prof::PutDebugSettingsProfError),
    #[error("Get_config error: {0:?}")]
    GetConfig(get_config::GetConfigError),
    #[error("Account_information error: {0:?}")]
    AccountInformation(account_information::AccountInformationError),
    #[error("Account_asset_information error: {0:?}")]
    AccountAssetInformation(account_asset_information::AccountAssetInformationError),
    #[error("Account_assets_information error: {0:?}")]
    AccountAssetsInformation(account_assets_information::AccountAssetsInformationError),
    #[error("Account_application_information error: {0:?}")]
    AccountApplicationInformation(account_application_information::AccountApplicationInformationError),
    #[error("Get_pending_transactions_by_address error: {0:?}")]
    GetPendingTransactionsByAddress(get_pending_transactions_by_address::GetPendingTransactionsByAddressError),
    #[error("Get_block error: {0:?}")]
    GetBlock(get_block::GetBlockError),
    #[error("Get_block_txids error: {0:?}")]
    GetBlockTxids(get_block_txids::GetBlockTxidsError),
    #[error("Get_block_hash error: {0:?}")]
    GetBlockHash(get_block_hash::GetBlockHashError),
    #[error("Get_transaction_proof error: {0:?}")]
    GetTransactionProof(get_transaction_proof::GetTransactionProofError),
    #[error("Get_block_logs error: {0:?}")]
    GetBlockLogs(get_block_logs::GetBlockLogsError),
    #[error("Get_supply error: {0:?}")]
    GetSupply(get_supply::GetSupplyError),
    #[error("Get_participation_keys error: {0:?}")]
    GetParticipationKeys(get_participation_keys::GetParticipationKeysError),
    #[error("Add_participation_key error: {0:?}")]
    AddParticipationKey(add_participation_key::AddParticipationKeyError),
    #[error("Generate_participation_keys error: {0:?}")]
    GenerateParticipationKeys(generate_participation_keys::GenerateParticipationKeysError),
    #[error("Get_participation_key_by_id error: {0:?}")]
    GetParticipationKeyById(get_participation_key_by_id::GetParticipationKeyByIdError),
    #[error("Append_keys error: {0:?}")]
    AppendKeys(append_keys::AppendKeysError),
    #[error("Delete_participation_key_by_id error: {0:?}")]
    DeleteParticipationKeyById(delete_participation_key_by_id::DeleteParticipationKeyByIdError),
    #[error("Shutdown_node error: {0:?}")]
    ShutdownNode(shutdown_node::ShutdownNodeError),
    #[error("Get_status error: {0:?}")]
    GetStatus(get_status::GetStatusError),
    #[error("Wait_for_block error: {0:?}")]
    WaitForBlock(wait_for_block::WaitForBlockError),
    #[error("Raw_transaction error: {0:?}")]
    RawTransaction(raw_transaction::RawTransactionError),
    #[error("Raw_transaction_async error: {0:?}")]
    RawTransactionAsync(raw_transaction_async::RawTransactionAsyncError),
    #[error("Simulate_transaction error: {0:?}")]
    SimulateTransaction(simulate_transaction::SimulateTransactionError),
    #[error("Transaction_params error: {0:?}")]
    TransactionParams(transaction_params::TransactionParamsError),
    #[error("Get_pending_transactions error: {0:?}")]
    GetPendingTransactions(get_pending_transactions::GetPendingTransactionsError),
    #[error("Pending_transaction_information error: {0:?}")]
    PendingTransactionInformation(pending_transaction_information::PendingTransactionInformationError),
    #[error("Get_ledger_state_delta error: {0:?}")]
    GetLedgerStateDelta(get_ledger_state_delta::GetLedgerStateDeltaError),
    #[error("Get_transaction_group_ledger_state_deltas_for_round error: {0:?}")]
    GetTransactionGroupLedgerStateDeltasForRound(get_transaction_group_ledger_state_deltas_for_round::GetTransactionGroupLedgerStateDeltasForRoundError),
    #[error("Get_ledger_state_delta_for_transaction_group error: {0:?}")]
    GetLedgerStateDeltaForTransactionGroup(get_ledger_state_delta_for_transaction_group::GetLedgerStateDeltaForTransactionGroupError),
    #[error("Get_state_proof error: {0:?}")]
    GetStateProof(get_state_proof::GetStateProofError),
    #[error("Get_light_block_header_proof error: {0:?}")]
    GetLightBlockHeaderProof(get_light_block_header_proof::GetLightBlockHeaderProofError),
    #[error("Get_application_by_id error: {0:?}")]
    GetApplicationById(get_application_by_id::GetApplicationByIdError),
    #[error("Get_application_boxes error: {0:?}")]
    GetApplicationBoxes(get_application_boxes::GetApplicationBoxesError),
    #[error("Get_application_box_by_name error: {0:?}")]
    GetApplicationBoxByName(get_application_box_by_name::GetApplicationBoxByNameError),
    #[error("Get_asset_by_id error: {0:?}")]
    GetAssetById(get_asset_by_id::GetAssetByIdError),
    #[error("Get_sync_round error: {0:?}")]
    GetSyncRound(get_sync_round::GetSyncRoundError),
    #[error("Unset_sync_round error: {0:?}")]
    UnsetSyncRound(unset_sync_round::UnsetSyncRoundError),
    #[error("Set_sync_round error: {0:?}")]
    SetSyncRound(set_sync_round::SetSyncRoundError),
    #[error("Teal_compile error: {0:?}")]
    TealCompile(teal_compile::TealCompileError),
    #[error("Teal_disassemble error: {0:?}")]
    TealDisassemble(teal_disassemble::TealDisassembleError),
    #[error("Start_catchup error: {0:?}")]
    StartCatchup(start_catchup::StartCatchupError),
    #[error("Abort_catchup error: {0:?}")]
    AbortCatchup(abort_catchup::AbortCatchupError),
    #[error("Teal_dryrun error: {0:?}")]
    TealDryrun(teal_dryrun::TealDryrunError),
    #[error("Experimental_check error: {0:?}")]
    ExperimentalCheck(experimental_check::ExperimentalCheckError),
    #[error("Get_block_time_stamp_offset error: {0:?}")]
    GetBlockTimeStampOffset(get_block_time_stamp_offset::GetBlockTimeStampOffsetError),
    #[error("Set_block_time_stamp_offset error: {0:?}")]
    SetBlockTimeStampOffset(set_block_time_stamp_offset::SetBlockTimeStampOffsetError),
    #[error("Unknown API error: {0}")]
    Unknown(String),
}

impl From<health_check::HealthCheckError> for AlgodApiError {
    fn from(err: health_check::HealthCheckError) -> Self {
        AlgodApiError::HealthCheck(err)
    }
}

impl From<get_ready::GetReadyError> for AlgodApiError {
    fn from(err: get_ready::GetReadyError) -> Self {
        AlgodApiError::GetReady(err)
    }
}

impl From<metrics::MetricsError> for AlgodApiError {
    fn from(err: metrics::MetricsError) -> Self {
        AlgodApiError::Metrics(err)
    }
}

impl From<get_genesis::GetGenesisError> for AlgodApiError {
    fn from(err: get_genesis::GetGenesisError) -> Self {
        AlgodApiError::GetGenesis(err)
    }
}

impl From<swagger_json::SwaggerJsonError> for AlgodApiError {
    fn from(err: swagger_json::SwaggerJsonError) -> Self {
        AlgodApiError::SwaggerJson(err)
    }
}

impl From<get_version::GetVersionError> for AlgodApiError {
    fn from(err: get_version::GetVersionError) -> Self {
        AlgodApiError::GetVersion(err)
    }
}

impl From<get_debug_settings_prof::GetDebugSettingsProfError> for AlgodApiError {
    fn from(err: get_debug_settings_prof::GetDebugSettingsProfError) -> Self {
        AlgodApiError::GetDebugSettingsProf(err)
    }
}

impl From<put_debug_settings_prof::PutDebugSettingsProfError> for AlgodApiError {
    fn from(err: put_debug_settings_prof::PutDebugSettingsProfError) -> Self {
        AlgodApiError::PutDebugSettingsProf(err)
    }
}

impl From<get_config::GetConfigError> for AlgodApiError {
    fn from(err: get_config::GetConfigError) -> Self {
        AlgodApiError::GetConfig(err)
    }
}

impl From<account_information::AccountInformationError> for AlgodApiError {
    fn from(err: account_information::AccountInformationError) -> Self {
        AlgodApiError::AccountInformation(err)
    }
}

impl From<account_asset_information::AccountAssetInformationError> for AlgodApiError {
    fn from(err: account_asset_information::AccountAssetInformationError) -> Self {
        AlgodApiError::AccountAssetInformation(err)
    }
}

impl From<account_assets_information::AccountAssetsInformationError> for AlgodApiError {
    fn from(err: account_assets_information::AccountAssetsInformationError) -> Self {
        AlgodApiError::AccountAssetsInformation(err)
    }
}

impl From<account_application_information::AccountApplicationInformationError> for AlgodApiError {
    fn from(err: account_application_information::AccountApplicationInformationError) -> Self {
        AlgodApiError::AccountApplicationInformation(err)
    }
}

impl From<get_pending_transactions_by_address::GetPendingTransactionsByAddressError>
    for AlgodApiError
{
    fn from(
        err: get_pending_transactions_by_address::GetPendingTransactionsByAddressError,
    ) -> Self {
        AlgodApiError::GetPendingTransactionsByAddress(err)
    }
}

impl From<get_block::GetBlockError> for AlgodApiError {
    fn from(err: get_block::GetBlockError) -> Self {
        AlgodApiError::GetBlock(err)
    }
}

impl From<get_block_txids::GetBlockTxidsError> for AlgodApiError {
    fn from(err: get_block_txids::GetBlockTxidsError) -> Self {
        AlgodApiError::GetBlockTxids(err)
    }
}

impl From<get_block_hash::GetBlockHashError> for AlgodApiError {
    fn from(err: get_block_hash::GetBlockHashError) -> Self {
        AlgodApiError::GetBlockHash(err)
    }
}

impl From<get_transaction_proof::GetTransactionProofError> for AlgodApiError {
    fn from(err: get_transaction_proof::GetTransactionProofError) -> Self {
        AlgodApiError::GetTransactionProof(err)
    }
}

impl From<get_block_logs::GetBlockLogsError> for AlgodApiError {
    fn from(err: get_block_logs::GetBlockLogsError) -> Self {
        AlgodApiError::GetBlockLogs(err)
    }
}

impl From<get_supply::GetSupplyError> for AlgodApiError {
    fn from(err: get_supply::GetSupplyError) -> Self {
        AlgodApiError::GetSupply(err)
    }
}

impl From<get_participation_keys::GetParticipationKeysError> for AlgodApiError {
    fn from(err: get_participation_keys::GetParticipationKeysError) -> Self {
        AlgodApiError::GetParticipationKeys(err)
    }
}

impl From<add_participation_key::AddParticipationKeyError> for AlgodApiError {
    fn from(err: add_participation_key::AddParticipationKeyError) -> Self {
        AlgodApiError::AddParticipationKey(err)
    }
}

impl From<generate_participation_keys::GenerateParticipationKeysError> for AlgodApiError {
    fn from(err: generate_participation_keys::GenerateParticipationKeysError) -> Self {
        AlgodApiError::GenerateParticipationKeys(err)
    }
}

impl From<get_participation_key_by_id::GetParticipationKeyByIdError> for AlgodApiError {
    fn from(err: get_participation_key_by_id::GetParticipationKeyByIdError) -> Self {
        AlgodApiError::GetParticipationKeyById(err)
    }
}

impl From<append_keys::AppendKeysError> for AlgodApiError {
    fn from(err: append_keys::AppendKeysError) -> Self {
        AlgodApiError::AppendKeys(err)
    }
}

impl From<delete_participation_key_by_id::DeleteParticipationKeyByIdError> for AlgodApiError {
    fn from(err: delete_participation_key_by_id::DeleteParticipationKeyByIdError) -> Self {
        AlgodApiError::DeleteParticipationKeyById(err)
    }
}

impl From<shutdown_node::ShutdownNodeError> for AlgodApiError {
    fn from(err: shutdown_node::ShutdownNodeError) -> Self {
        AlgodApiError::ShutdownNode(err)
    }
}

impl From<get_status::GetStatusError> for AlgodApiError {
    fn from(err: get_status::GetStatusError) -> Self {
        AlgodApiError::GetStatus(err)
    }
}

impl From<wait_for_block::WaitForBlockError> for AlgodApiError {
    fn from(err: wait_for_block::WaitForBlockError) -> Self {
        AlgodApiError::WaitForBlock(err)
    }
}

impl From<raw_transaction::RawTransactionError> for AlgodApiError {
    fn from(err: raw_transaction::RawTransactionError) -> Self {
        AlgodApiError::RawTransaction(err)
    }
}

impl From<raw_transaction_async::RawTransactionAsyncError> for AlgodApiError {
    fn from(err: raw_transaction_async::RawTransactionAsyncError) -> Self {
        AlgodApiError::RawTransactionAsync(err)
    }
}

impl From<simulate_transaction::SimulateTransactionError> for AlgodApiError {
    fn from(err: simulate_transaction::SimulateTransactionError) -> Self {
        AlgodApiError::SimulateTransaction(err)
    }
}

impl From<transaction_params::TransactionParamsError> for AlgodApiError {
    fn from(err: transaction_params::TransactionParamsError) -> Self {
        AlgodApiError::TransactionParams(err)
    }
}

impl From<get_pending_transactions::GetPendingTransactionsError> for AlgodApiError {
    fn from(err: get_pending_transactions::GetPendingTransactionsError) -> Self {
        AlgodApiError::GetPendingTransactions(err)
    }
}

impl From<pending_transaction_information::PendingTransactionInformationError> for AlgodApiError {
    fn from(err: pending_transaction_information::PendingTransactionInformationError) -> Self {
        AlgodApiError::PendingTransactionInformation(err)
    }
}

impl From<get_ledger_state_delta::GetLedgerStateDeltaError> for AlgodApiError {
    fn from(err: get_ledger_state_delta::GetLedgerStateDeltaError) -> Self {
        AlgodApiError::GetLedgerStateDelta(err)
    }
}

impl From<get_transaction_group_ledger_state_deltas_for_round::GetTransactionGroupLedgerStateDeltasForRoundError> for AlgodApiError {
    fn from(err: get_transaction_group_ledger_state_deltas_for_round::GetTransactionGroupLedgerStateDeltasForRoundError) -> Self {
        AlgodApiError::GetTransactionGroupLedgerStateDeltasForRound(err)
    }
}

impl From<get_ledger_state_delta_for_transaction_group::GetLedgerStateDeltaForTransactionGroupError>
    for AlgodApiError
{
    fn from(
        err: get_ledger_state_delta_for_transaction_group::GetLedgerStateDeltaForTransactionGroupError,
    ) -> Self {
        AlgodApiError::GetLedgerStateDeltaForTransactionGroup(err)
    }
}

impl From<get_state_proof::GetStateProofError> for AlgodApiError {
    fn from(err: get_state_proof::GetStateProofError) -> Self {
        AlgodApiError::GetStateProof(err)
    }
}

impl From<get_light_block_header_proof::GetLightBlockHeaderProofError> for AlgodApiError {
    fn from(err: get_light_block_header_proof::GetLightBlockHeaderProofError) -> Self {
        AlgodApiError::GetLightBlockHeaderProof(err)
    }
}

impl From<get_application_by_id::GetApplicationByIdError> for AlgodApiError {
    fn from(err: get_application_by_id::GetApplicationByIdError) -> Self {
        AlgodApiError::GetApplicationById(err)
    }
}

impl From<get_application_boxes::GetApplicationBoxesError> for AlgodApiError {
    fn from(err: get_application_boxes::GetApplicationBoxesError) -> Self {
        AlgodApiError::GetApplicationBoxes(err)
    }
}

impl From<get_application_box_by_name::GetApplicationBoxByNameError> for AlgodApiError {
    fn from(err: get_application_box_by_name::GetApplicationBoxByNameError) -> Self {
        AlgodApiError::GetApplicationBoxByName(err)
    }
}

impl From<get_asset_by_id::GetAssetByIdError> for AlgodApiError {
    fn from(err: get_asset_by_id::GetAssetByIdError) -> Self {
        AlgodApiError::GetAssetById(err)
    }
}

impl From<get_sync_round::GetSyncRoundError> for AlgodApiError {
    fn from(err: get_sync_round::GetSyncRoundError) -> Self {
        AlgodApiError::GetSyncRound(err)
    }
}

impl From<unset_sync_round::UnsetSyncRoundError> for AlgodApiError {
    fn from(err: unset_sync_round::UnsetSyncRoundError) -> Self {
        AlgodApiError::UnsetSyncRound(err)
    }
}

impl From<set_sync_round::SetSyncRoundError> for AlgodApiError {
    fn from(err: set_sync_round::SetSyncRoundError) -> Self {
        AlgodApiError::SetSyncRound(err)
    }
}

impl From<teal_compile::TealCompileError> for AlgodApiError {
    fn from(err: teal_compile::TealCompileError) -> Self {
        AlgodApiError::TealCompile(err)
    }
}

impl From<teal_disassemble::TealDisassembleError> for AlgodApiError {
    fn from(err: teal_disassemble::TealDisassembleError) -> Self {
        AlgodApiError::TealDisassemble(err)
    }
}

impl From<start_catchup::StartCatchupError> for AlgodApiError {
    fn from(err: start_catchup::StartCatchupError) -> Self {
        AlgodApiError::StartCatchup(err)
    }
}

impl From<abort_catchup::AbortCatchupError> for AlgodApiError {
    fn from(err: abort_catchup::AbortCatchupError) -> Self {
        AlgodApiError::AbortCatchup(err)
    }
}

impl From<teal_dryrun::TealDryrunError> for AlgodApiError {
    fn from(err: teal_dryrun::TealDryrunError) -> Self {
        AlgodApiError::TealDryrun(err)
    }
}

impl From<experimental_check::ExperimentalCheckError> for AlgodApiError {
    fn from(err: experimental_check::ExperimentalCheckError) -> Self {
        AlgodApiError::ExperimentalCheck(err)
    }
}

impl From<get_block_time_stamp_offset::GetBlockTimeStampOffsetError> for AlgodApiError {
    fn from(err: get_block_time_stamp_offset::GetBlockTimeStampOffsetError) -> Self {
        AlgodApiError::GetBlockTimeStampOffset(err)
    }
}

impl From<set_block_time_stamp_offset::SetBlockTimeStampOffsetError> for AlgodApiError {
    fn from(err: set_block_time_stamp_offset::SetBlockTimeStampOffsetError) -> Self {
        AlgodApiError::SetBlockTimeStampOffset(err)
    }
}

/// The main error type for all algod client operations
#[derive(Debug, thiserror::Error)]
pub enum Error {
    #[error("HTTP error: {0}")]
    Http(#[from] algokit_http_client::HttpError),
    #[error("Serialization error: {0}")]
    Serde(String),
    #[error("API error: {0}")]
    Api(#[from] AlgodApiError),
}

#[derive(Debug, PartialEq, Eq)]
pub enum ContentType {
    Json,
    MsgPack,
    Text,
    Unsupported(String),
}

impl From<&str> for ContentType {
    fn from(content_type: &str) -> Self {
        if content_type.contains("application/json") {
            ContentType::Json
        } else if content_type.contains("application/msgpack") {
            ContentType::MsgPack
        } else if content_type.contains("text/plain") {
            ContentType::Text
        } else {
            ContentType::Unsupported(content_type.to_string())
        }
    }
}

pub fn urlencode<T: AsRef<str>>(s: T) -> String {
    ::url::form_urlencoded::byte_serialize(s.as_ref().as_bytes()).collect()
}

// Re-export the consolidated client
pub use client::AlgodClient;

// Re-export parameter enums
pub use parameter_enums::*;

// Re-export all endpoint functions
pub use abort_catchup::{AbortCatchupError, abort_catchup};
pub use account_application_information::{
    AccountApplicationInformationError, account_application_information,
};
pub use account_asset_information::{AccountAssetInformationError, account_asset_information};
pub use account_assets_information::{AccountAssetsInformationError, account_assets_information};
pub use account_information::{AccountInformationError, account_information};
pub use add_participation_key::{AddParticipationKeyError, add_participation_key};
pub use append_keys::{AppendKeysError, append_keys};
pub use delete_participation_key_by_id::{
    DeleteParticipationKeyByIdError, delete_participation_key_by_id,
};
pub use experimental_check::{ExperimentalCheckError, experimental_check};
pub use generate_participation_keys::{
    GenerateParticipationKeysError, generate_participation_keys,
};
pub use get_application_box_by_name::{GetApplicationBoxByNameError, get_application_box_by_name};
pub use get_application_boxes::{GetApplicationBoxesError, get_application_boxes};
pub use get_application_by_id::{GetApplicationByIdError, get_application_by_id};
pub use get_asset_by_id::{GetAssetByIdError, get_asset_by_id};
pub use get_block::{GetBlockError, get_block};
pub use get_block_hash::{GetBlockHashError, get_block_hash};
pub use get_block_logs::{GetBlockLogsError, get_block_logs};
pub use get_block_time_stamp_offset::{GetBlockTimeStampOffsetError, get_block_time_stamp_offset};
pub use get_block_txids::{GetBlockTxidsError, get_block_txids};
pub use get_config::{GetConfigError, get_config};
pub use get_debug_settings_prof::{GetDebugSettingsProfError, get_debug_settings_prof};
pub use get_genesis::{GetGenesisError, get_genesis};
pub use get_ledger_state_delta::{GetLedgerStateDeltaError, get_ledger_state_delta};
pub use get_ledger_state_delta_for_transaction_group::{
    GetLedgerStateDeltaForTransactionGroupError, get_ledger_state_delta_for_transaction_group,
};
pub use get_light_block_header_proof::{
    GetLightBlockHeaderProofError, get_light_block_header_proof,
};
pub use get_participation_key_by_id::{GetParticipationKeyByIdError, get_participation_key_by_id};
pub use get_participation_keys::{GetParticipationKeysError, get_participation_keys};
pub use get_pending_transactions::{GetPendingTransactionsError, get_pending_transactions};
pub use get_pending_transactions_by_address::{
    GetPendingTransactionsByAddressError, get_pending_transactions_by_address,
};
pub use get_ready::{GetReadyError, get_ready};
pub use get_state_proof::{GetStateProofError, get_state_proof};
pub use get_status::{GetStatusError, get_status};
pub use get_supply::{GetSupplyError, get_supply};
pub use get_sync_round::{GetSyncRoundError, get_sync_round};
pub use get_transaction_group_ledger_state_deltas_for_round::{
    GetTransactionGroupLedgerStateDeltasForRoundError,
    get_transaction_group_ledger_state_deltas_for_round,
};
pub use get_transaction_proof::{GetTransactionProofError, get_transaction_proof};
pub use get_version::{GetVersionError, get_version};
pub use health_check::{HealthCheckError, health_check};
pub use metrics::{MetricsError, metrics};
pub use pending_transaction_information::{
    PendingTransactionInformationError, pending_transaction_information,
};
pub use put_debug_settings_prof::{PutDebugSettingsProfError, put_debug_settings_prof};
pub use raw_transaction::{RawTransactionError, raw_transaction};
pub use raw_transaction_async::{RawTransactionAsyncError, raw_transaction_async};
pub use set_block_time_stamp_offset::{SetBlockTimeStampOffsetError, set_block_time_stamp_offset};
pub use set_sync_round::{SetSyncRoundError, set_sync_round};
pub use shutdown_node::{ShutdownNodeError, shutdown_node};
pub use simulate_transaction::{SimulateTransactionError, simulate_transaction};
pub use start_catchup::{StartCatchupError, start_catchup};
pub use swagger_json::{SwaggerJsonError, swagger_json};
pub use teal_compile::{TealCompileError, teal_compile};
pub use teal_disassemble::{TealDisassembleError, teal_disassemble};
pub use teal_dryrun::{TealDryrunError, teal_dryrun};
pub use transaction_params::{TransactionParamsError, transaction_params};
pub use unset_sync_round::{UnsetSyncRoundError, unset_sync_round};
pub use wait_for_block::{WaitForBlockError, wait_for_block};
