/**
 * Algod REST API.
 * API endpoint for algod operations.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@algorand.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class GenesisAllocationState {
    'algo': number | bigint;
    'onl'?: number;
    'sel'?: string;
    'stprf'?: string;
    'vote'?: string;
    'voteKD'?: number | bigint;
    'voteFst'?: number | bigint;
    'voteLst'?: number | bigint;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "algo",
            "baseName": "algo",
            "type": "bigint",
            "format": "uint64"
        },
        {
            "name": "onl",
            "baseName": "onl",
            "type": "number",
            "format": ""
        },
        {
            "name": "sel",
            "baseName": "sel",
            "type": "string",
            "format": ""
        },
        {
            "name": "stprf",
            "baseName": "stprf",
            "type": "string",
            "format": ""
        },
        {
            "name": "vote",
            "baseName": "vote",
            "type": "string",
            "format": ""
        },
        {
            "name": "voteKD",
            "baseName": "voteKD",
            "type": "bigint",
            "format": "uint64"
        },
        {
            "name": "voteFst",
            "baseName": "voteFst",
            "type": "bigint",
            "format": "uint64"
        },
        {
            "name": "voteLst",
            "baseName": "voteLst",
            "type": "bigint",
            "format": "uint64"
        }    ];

    static getAttributeTypeMap() {
        return GenesisAllocationState.attributeTypeMap;
    }

    public constructor() {
    }
}
