/**
 * Algod REST API.
 * API endpoint for algod operations.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@algorand.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GenesisAllocationState } from '../models/GenesisAllocationState';
import { HttpFile } from '../http/http';

export class GenesisAllocation {
    'addr': string;
    'comment': string;
    'state': GenesisAllocationState;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "addr",
            "baseName": "addr",
            "type": "string",
            "format": ""
        },
        {
            "name": "comment",
            "baseName": "comment",
            "type": "string",
            "format": ""
        },
        {
            "name": "state",
            "baseName": "state",
            "type": "GenesisAllocationState",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GenesisAllocation.attributeTypeMap;
    }

    public constructor() {
    }
}
