/**
 * Algod REST API.
 * API endpoint for algod operations.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@algorand.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GenesisAllocation } from '../models/GenesisAllocation';
import { HttpFile } from '../http/http';

export class Genesis {
    'alloc': Array<GenesisAllocation>;
    'comment'?: string;
    'devmode'?: boolean;
    'fees': string;
    'id': string;
    'network': string;
    'proto': string;
    'rwd': string;
    'timestamp': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "alloc",
            "baseName": "alloc",
            "type": "Array<GenesisAllocation>",
            "format": ""
        },
        {
            "name": "comment",
            "baseName": "comment",
            "type": "string",
            "format": ""
        },
        {
            "name": "devmode",
            "baseName": "devmode",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "fees",
            "baseName": "fees",
            "type": "string",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "network",
            "baseName": "network",
            "type": "string",
            "format": ""
        },
        {
            "name": "proto",
            "baseName": "proto",
            "type": "string",
            "format": ""
        },
        {
            "name": "rwd",
            "baseName": "rwd",
            "type": "string",
            "format": ""
        },
        {
            "name": "timestamp",
            "baseName": "timestamp",
            "type": "number",
            "format": "int64"
        }    ];

    static getAttributeTypeMap() {
        return Genesis.attributeTypeMap;
    }

    public constructor() {
    }
}
