/**
 * Algod REST API.
 * API endpoint for algod operations.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@algorand.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* A single Delta containing the key, the previous value and the current value for a single round.
*/
export class KvDelta {
    /**
    * The key, base64 encoded.
    */
    'key'?: string;
    /**
    * The new value of the KV store entry, base64 encoded.
    */
    'value'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "key",
            "baseName": "key",
            "type": "string",
            "format": "byte"
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "string",
            "format": "byte"
        }    ];

    static getAttributeTypeMap() {
        return KvDelta.attributeTypeMap;
    }

    public constructor() {
    }
}
