templateDir: oas_templates/python
additionalProperties:
    packageVersion: "1.0.0a19"
    packageName: algokit_algod_api
    licenseInfo: MIT

openapiNormalizer:
    SET_TAGS_FOR_ALL_OPERATIONS: Algod

files:
    # Section for dropping custom tests
    custom_tests/test_transactions.mustache:
        templateType: SupportingFiles
        destinationFilename: tests/api/test_transactions.py
    custom_tests/test_accounts.mustache:
        templateType: SupportingFiles
        destinationFilename: tests/api/test_accounts.py
    custom_tests/__init__.mustache:
        templateType: SupportingFiles
        destinationFilename: tests/api/__init__.py
    conftest.mustache:
        templateType: SupportingFiles
        destinationFilename: tests/conftest.py
    custom_tests/utils.mustache:
        templateType: SupportingFiles
        destinationFilename: tests/utils.py
    custom_tests/artifacts/dummy_app.arc56.mustache:
        templateType: SupportingFiles
        destinationFilename: tests/artifacts/dummy_app.arc56.json
    # Generic supporting files
    poetry.toml.mustache:
        templateType: SupportingFiles
        destinationFilename: poetry.toml
    pytest_ini.mustache:
        templateType: SupportingFiles
        destinationFilename: pytest.ini
    .vscode/settings.mustache:
        templateType: SupportingFiles
        destinationFilename: .vscode/settings.json
